### ISSUE TITLE
I get this error how can I solve it? -----------  with mp_pose.Pose(upper_body_only=False) as pose_tracker: TypeError: Pose.__init__() got an unexpected keyword argument 'upper_body_only'

### ISSUE THREAD

**Issue by Joseluisrigolino** [dawi9840/knn_pose_classification_create_csv#2]
Bootstrapping:  ataque_posicion_caminar
  0%|                                                     | 0/315 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\Users\HP\Desktop\knn_pose_classification_create_csv-main\csv_create.py", line 110, in <module>
    main(bootstrap_images_in_folder, bootstrap_images_out_folder, bootstrap_csvs_out_folder, export_csv)
  File "c:\Users\HP\Desktop\knn_pose_classification_create_csv-main\csv_create.py", line 47, in main
    bootstrap_helper.bootstrap()
  File "c:\Users\HP\Desktop\knn_pose_classification_create_csv-main\bootstrap_helper.py", line 87, in bootstrap
    with mp_pose.Pose(upper_body_only=False) as pose_tracker:
TypeError: Pose.__init__() got an unexpected keyword argument 'upper_body_only'

**Comment by dawi9840** [comment]
Is your mediapipe package version 0.8.3? I guess that was maybe the difference version result invoke Pose.init() to get the error.
